FROM python:3.10-slim

WORKDIR /

COPY requirements.txt /requirements.txt
RUN pip install --upgrade pip && pip install -r requirements.txt

# Clone Wan2.2 from GitHub
RUN apt-get update && \
    apt-get install -y --no-install-recommends git && \
    git clone https://github.com/Wan-Video/Wan2.2.git /wan2

# Install Wan2.2 requirements
RUN pip install -r /wan2/requirements.txt

# Install Wan2.2 itself
RUN pip install /wan2

COPY rp_handler.py /

# Start the container
CMD ["python3", "-u", "rp_handler.py"]